RoleBasedAccessMVC/RoleBasedAccessMVC/RoleBasedAccessMVC/Controllers/HrController.cs
using RoleBasedAccess.Model;
using RoleBasedAccessMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RoleBasedAccessMVC.Controllers
{
    [Authorize]
    public class HrController : Controller
    {
          [Authorize(Roles = "HR")]
        public ActionResult AddEmployee()
        {
            ViewData["Success"]="";
            return View("AddEmployee");
        }
          [Authorize(Roles = "HR")]
        public ActionResult SaveEmployee(Employee model)
        {
            
            EmployeeResponse responseEmployee = null;
            try
            {
                 responseEmployee = model.CreateEmployee();
            }
            catch (Exception e)
            {
            }
            if (string.Equals(responseEmployee.Status.StatusCode, "200", StringComparison.OrdinalIgnoreCase) == false)
            {
                ViewData["Success"] = "Employee Creadtion Failed";
                ModelState.Clear();
                return View("AddEmployee");
                
            }
            ViewData["Success"] = "Employee Creadtion Successful";
            ModelState.Clear();
            return View("AddEmployee");
        }
          [Authorize(Roles = "HR")]
        public ActionResult AddRemark()
        {

            ViewData["Success"] = "";
            ViewData["RemarkList"] = this.GetAllEmployee();
            if(ViewData["Success"].ToString().Equals(""))
            ViewData["Success"] = "";
            
            return View("AddRemark");
        }
          [Authorize(Roles = "HR")]
        private List<SelectListItem> GetAllEmployee()
        {
            GetAllEmployeeResponse employeeListResponse = GetAllEmployeeResponse.GetAllEmployee();

            if (string.Equals(employeeListResponse.Status.StatusCode, "200", StringComparison.OrdinalIgnoreCase) == false)
            {
                ViewData["Success"] = "Fetch Employee Failed";
            }
            List<Employee> employeeList = employeeListResponse.AllEmployeeList;
            List<SelectListItem> employeeDetails = new List<SelectListItem>();
            foreach (var employee in employeeList)
            {
                employeeDetails.Add(new SelectListItem { Text = (employee.FirstName.Trim() + " " + employee.LastName.Trim()), Value = employee.Id.Trim() });
            }
            return employeeDetails;

        }
          [Authorize(Roles = "HR")]
        public ActionResult SaveRemark(Remark model)
        {
            model.DateTime = DateTime.UtcNow;

            string selectedEmployee = Request["SelectedEmployee"].ToString();
            RemarkResponse responseRemark = model.AddRemark(selectedEmployee);
           
            if (string.Equals(responseRemark.Status.StatusCode, "200", StringComparison.OrdinalIgnoreCase) == false)
            {
                ViewData["Success"]= "Add Remark Failed";
                ModelState.Clear();
                return View("AddRemark");
            }
            ViewData["Success"] = "Add Remark Successful";
            ViewData["RemarkList"] = this.GetAllEmployee();
            ModelState.Clear();
            return View("AddRemark");
        }

    }
}

RoleBasedAccessMVC/RoleBasedAccessMVC/RoleBasedAccessMVC/Views/Hr/AddEmployee.cshtml
@model RoleBasedAccess.Model.Employee

@{
    ViewBag.Title = "AddEmployee";
}

<h2>AddEmployee</h2>
@using (Html.BeginForm("SaveEmployee", "Hr")) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()
    }
<div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
            @Html.ActionLink("Add Employee", "AddEmployee", "Hr")
            @Html.ActionLink("Add Remark", "AddRemark", "Hr")
        @Html.ActionLink("Change Password", "Manage", "Account")
    </ul>
</div>
<form action="/Hr/SaveEmployee" method="post">
<fieldset>
        <legend>Add Employee Form</legend>
        <ol>
            <li>
                @Html.Label(ViewData["Success"].ToString())
            </li>
            <li>
                @Html.LabelFor(m => m.Title)
                @Html.TextBoxFor(m => m.Title)
                @Html.ValidationMessageFor(m => m.Title)
            </li>
             <li>
                @Html.LabelFor(m => m.FirstName)
                @Html.TextBoxFor(m => m.FirstName)
                @Html.ValidationMessageFor(m => m.FirstName)
            </li>
             <li>
                @Html.LabelFor(m => m.LastName)
                @Html.TextBoxFor(m => m.LastName)
                @Html.ValidationMessageFor(m => m.LastName)
            </li>
             <li>
                @Html.LabelFor(m => m.Email)
                @Html.TextBoxFor(m => m.Email)
                @Html.ValidationMessageFor(m => m.Email)
            </li>
             <li>
                @Html.LabelFor(m => m.Designation)
                @Html.TextBoxFor(m => m.Designation)
                @Html.ValidationMessageFor(m => m.Designation)
            </li>
           
        </ol>
        <input type="submit" value="Add Employee" />
    </fieldset>
    </form>

RoleBasedAccessMVC/RoleBasedAccessMVC/RoleBasedAccessMVC/Views/Hr/AddRemark.cshtml
@model RoleBasedAccess.Model.Remark

@{
    ViewBag.Title = "AddRemark";
}

<h2>AddRemark</h2>
@using (Html.BeginForm("SaveRemark", "Hr")) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()
    }
<div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
            @Html.ActionLink("Add Employee", "AddEmployee", "Hr")
            @Html.ActionLink("Add Remark", "AddRemark", "Hr")
         @Html.ActionLink("Change Password", "Manage", "Account")
    </ul>
</div>
<form action="/Hr/SaveRemark" method="post">
<fieldset>
        <legend>Log in Form</legend>
        <ol>
            <li>
                @Html.Label(ViewData["Success"].ToString())
            </li>
            <li>
                @Html.Label("Select Employee")
                @Html.DropDownList("SelectedEmployee", ViewData["RemarkList"] as List<SelectListItem>)
              
            </li>
             <li>
                @Html.LabelFor(m => m.Text)
                @Html.TextBoxFor(m => m.Text)
                @Html.ValidationMessageFor(m => m.Text)
            </li>
           
        </ol>
        <input type="submit" value="Add Remark" />
    </fieldset>
    </form>